//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2832
        ///2108
        ///3082
        ///4328
        ///6843
        ///5121
        ///2869
        ///1366
        ///2358
        ///1680
        ///4980
        ///1161
        ///
        ///8026
        ///2154
        ///4242
        ///1023
        ///2744
        ///3162
        ///4093
        ///1150
        ///5397
        ///2738
        ///5657
        ///
        ///10954
        ///11208
        ///8034
        ///1636
        ///9430
        ///9421
        ///5025
        ///
        ///3837
        ///5938
        ///3967
        ///2942
        ///2727
        ///3623
        ///4070
        ///1748
        ///1795
        ///1687
        ///4023
        ///6068
        ///2558
        ///2570
        ///4214
        ///
        ///9679
        ///2986
        ///5168
        ///16463
        ///
        ///5912
        ///6008
        ///1259
        ///5378
        ///10740
        ///1642
        ///2617
        ///7821
        ///
        ///3840
        ///5265
        ///2104
        ///1510
        ///5477
        ///2636
        ///5920
        ///5939
        ///5430
        ///4482
        ///5603
        ///4915
        ///5416
        ///5897
        ///
        ///3932
        ///9344
        ///7536
        ///4925
        ///10088
        ///5253
        ///5625
        ///6800
        ///
        ///3928
        ///13714
        ///1899 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01 {
            get {
                return ResourceManager.GetString("Day01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B Z
        ///B Z
        ///B Y
        ///C Y
        ///B Y
        ///C Y
        ///C Y
        ///A Z
        ///B Y
        ///A Y
        ///C X
        ///A Y
        ///A Y
        ///C Y
        ///A Y
        ///B Y
        ///B Y
        ///C Y
        ///A Y
        ///A Y
        ///A Y
        ///C Y
        ///A Y
        ///B Y
        ///A Y
        ///B Y
        ///C Y
        ///B X
        ///A X
        ///A Y
        ///C X
        ///B Y
        ///C Y
        ///B Y
        ///B X
        ///C X
        ///B Y
        ///B Y
        ///A Y
        ///A X
        ///A X
        ///A Y
        ///B Y
        ///C Y
        ///C X
        ///A X
        ///B Y
        ///C Z
        ///B Y
        ///C X
        ///A Y
        ///A X
        ///C X
        ///A Y
        ///A Y
        ///A Y
        ///A Y
        ///B X
        ///C Y
        ///C Z
        ///B Y
        ///C Y
        ///A Y
        ///A Y
        ///B Y
        ///A Y
        ///C X
        ///B Y
        ///C Y
        ///C Y
        ///A Y
        ///C X
        ///B Y
        ///A Y
        ///B Y
        ///C Y
        ///C Y
        ///A Y
        ///B Y
        ///C Y
        ///C Y
        ///C Y
        ///A X
        ///A X
        ///B Y
        ///B Y
        ///C Z
        ///C Y
        ///B Y
        ///B Y
        ///B Y
        ///C Y
        ///A Y
        ///C Y
        ///A Y
        ///A Y
        ///A X
        ///C Y
        ///A X
        ///A Y
        ///A Y
        ///B Y
        ///B  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02 {
            get {
                return ResourceManager.GetString("Day02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BdbzzddChsWrRFbzBrszbhWMLNJHLLLLHZtSLglFNZHLJH
        ///nnfMwqpQTMffHlNNLllHnZSS
        ///cGpcMwfppfqcjcTCBBzWDsDbDrjzWz
        ///LhfjhcdjcGdhFfdGfdjdvwCCZMvvLvWwMLCLSwZC
        ///rDnsbmptPmlbQMCrQWQQBZQW
        ///gltgVPngDPbptPsbPzVgmDldfTdfczThjJJjfMcJdFHjjH
        ///dGlgDflTLLLrRLTLVdQLcQMnbvHbbFzNNvMbnHHn
        ///sZjWJJCSjWqfCqSjSmJSbFvCzBMBBzHncHNvMBHN
        ///twqqwpZwfrlwRwDGDR
        ///zCGGFTQMQrsNRNGZdR
        ///cLLQgPDpgcgmvPRHrwBdvrNZ
        ///glWpmJWQDcJpQnpjSmbhFtMnqFfCVTCFCFFM
        ///zNZWFNZBFrGTdBcZZBdJTrGrmgvppgDHwHmgVHCHCvCPDjzC
        ///qtqqPnLSfLwvjvvgvvqH
        ///MtbLLLQbRfPRfnbnnLMtnsbdBNsrGW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03 {
            get {
                return ResourceManager.GetString("Day03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-24,8-8
        ///2-75,37-51
        ///47-78,20-39
        ///53-91,34-53
        ///13-50,14-50
        ///93-93,20-93
        ///74-80,48-81
        ///30-87,27-38
        ///6-93,7-94
        ///56-98,12-49
        ///10-71,3-4
        ///87-95,55-88
        ///27-98,52-99
        ///4-11,11-82
        ///4-90,4-96
        ///3-89,4-80
        ///4-88,6-82
        ///69-75,70-76
        ///6-71,5-7
        ///91-96,8-74
        ///52-53,2-52
        ///9-94,10-97
        ///14-75,63-76
        ///3-26,3-4
        ///40-55,39-41
        ///17-22,4-80
        ///62-94,15-95
        ///37-77,6-76
        ///21-22,22-27
        ///3-94,93-98
        ///92-93,12-93
        ///80-81,6-80
        ///53-54,54-95
        ///45-90,44-91
        ///12-99,21-95
        ///36-69,35-68
        ///30-77,61-86
        ///24-49,23-78
        ///40-87,40-86
        ///36-53,53-54
        ///11-96,55-86
        ///31-41,4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04 {
            get {
                return ResourceManager.GetString("Day04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [N]             [R]             [C]
        ///[T] [J]         [S] [J]         [N]
        ///[B] [Z]     [H] [M] [Z]         [D]
        ///[S] [P]     [G] [L] [H] [Z]     [T]
        ///[Q] [D]     [F] [D] [V] [L] [S] [M]
        ///[H] [F] [V] [J] [C] [W] [P] [W] [L]
        ///[G] [S] [H] [Z] [Z] [T] [F] [V] [H]
        ///[R] [H] [Z] [M] [T] [M] [T] [Q] [W]
        /// 1   2   3   4   5   6   7   8   9 
        ///
        ///move 3 from 9 to 7
        ///move 4 from 4 to 5
        ///move 2 from 4 to 6
        ///move 4 from 7 to 5
        ///move 3 from 7 to 3
        ///move 2 from 5 to 9
        ///move 5 from 6 to 3
        ///move 5 from 9 to 1
        ///move 3 from 8 to  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day05 {
            get {
                return ResourceManager.GetString("Day05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bfdbbngnvnsvshhhrvrbrtbrrhqrqgrrmmdfmmqttptltntrntrnrcrdcrrctctdtwtrwwmlltcltcllmpprvvtbbmbvbsvvqwvvscswsqqgzqqppvzppnddjwddlrdlllmwllfccdfccswwrhhndhdhfdftdfdcdcllcjjbsbgssvlvrrhfrfjfpjffvnfvfwfzftztwwrhwrhwhwddpjjmhmgmsssstzszqzfqzzprpzpnndttphtpphvvcpcjppdtdwwqgwwwnhwnnvhvsvqqtrrbsscwssgwglgwlldjdzjjbsjbsbvvpbvppvfvqvbqbzzwtwbwpbbbcffdgggpnpfptpfphfhfthfthffzrrbzbcblbmmzmhhnvvqvlvwvzvtztgzznbbcqbccwhcwcnwnhndhhgcghhlthllplvppgngrgsswfsfnfjjswstsrtrhthhqzqggdtggzvvjljddqdzzrmrjmjcmjmrrwlldttrhhfjjgbglgjll [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day06 {
            get {
                return ResourceManager.GetString("Day06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day07 {
            get {
                return ResourceManager.GetString("Day07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day08 {
            get {
                return ResourceManager.GetString("Day08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day09 {
            get {
                return ResourceManager.GetString("Day09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day10 {
            get {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day11 {
            get {
                return ResourceManager.GetString("Day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day12 {
            get {
                return ResourceManager.GetString("Day12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day13 {
            get {
                return ResourceManager.GetString("Day13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day14 {
            get {
                return ResourceManager.GetString("Day14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day15 {
            get {
                return ResourceManager.GetString("Day15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day16 {
            get {
                return ResourceManager.GetString("Day16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day17 {
            get {
                return ResourceManager.GetString("Day17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day18 {
            get {
                return ResourceManager.GetString("Day18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day19 {
            get {
                return ResourceManager.GetString("Day19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day20 {
            get {
                return ResourceManager.GetString("Day20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day21 {
            get {
                return ResourceManager.GetString("Day21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day22 {
            get {
                return ResourceManager.GetString("Day22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day23 {
            get {
                return ResourceManager.GetString("Day23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day24 {
            get {
                return ResourceManager.GetString("Day24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day25 {
            get {
                return ResourceManager.GetString("Day25", resourceCulture);
            }
        }
    }
}
